### ISSUE TITLE
Resize-handle is higher than it needs

### ISSUE THREAD

**Issue by guopenghui** [contrapasso3/Reshi#2]
Dear Developer, Thank you for your beautiful theme, I was attracted by its simplicity and comfort and intend to use it as my own main use theme.

One such issue was found during use:
This `left-resize-handle` is a child of `left-split` and has height of `100%` of its parent. 
![image](https://github.com/contrapasso3/Reshi/assets/13451866/7627aca1-d8e0-489f-a9bf-600b362f8645)

![image](https://github.com/contrapasso3/Reshi/assets/13451866/82503f71-01c4-4a80-ac5f-c66b739ea0ff)

But meanwhile it has a css rule of `top: 39px !important;`:

![image](https://github.com/contrapasso3/Reshi/assets/13451866/dce0a4df-a490-4ab0-8632-1d0901d52d04)

These two rules make it overflow to its parent, like this:
![image](https://github.com/contrapasso3/Reshi/assets/13451866/12379fd9-9fe7-4453-8547-1ce00227f1bf)

When a plugin call `scrollIntoView` method to an element below the viewport, the whole view may move up and title bar will disappear:
 
before call: 
![image](https://github.com/contrapasso3/Reshi/assets/13451866/07ed4a5d-0df8-4cba-88c6-5ae4dfe89479)

after call:
![image](https://github.com/contrapasso3/Reshi/assets/13451866/a04b55f8-5ced-45bc-8ac0-d0d356d6feee)

As my test, a `height: auto` to `left-size-handle` can fix this.

**Comment by contrapasso3** [comment]
Hi! Thanks so much for your nice comment, I'm glad you enjoy the theme!

I changed the CSS to the following:

```
.workspace-leaf-resize-handle {
	top: 39px !important;
	height: var(--left-size-handle);
}
```

Does that fix the issue for you? If not I can open pull requests and you can suggest changes. I really appreciate the feedback!

**Comment by guopenghui** [comment]
I opened a PR #4 and made some change. Now in my app it works well.😉

**Comment by contrapasso3** [comment]
Thanks so much! I merged and will now close this issue.
